server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgresDb
    password: postgres
    username: postgres

logging:
  level:
    root: info
    org:
      springframework: warn
      hibernate: warn
    liquibase: warn

  file:
    path: ./logs/